food-site/mysite/food/urls.py
from django.urls import path

from . import views

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:item_id>/', views.item, name='item'),
    path('add', views.AddItemView.as_view(), name='add_item'),
    path('edit/<int:item_id>/', views.edit_item, name='edit_item'),
    path('delete/<int:item_id>/', views.delete_item, name='delete_item')
]

food-site/mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.user_logout, name='logout'),
    path('profile/', user_views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food-site/mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    image = models.CharField(max_length=500, default='https://w7.pngwing.com/pngs/1013/530/png-transparent-cafe-italian-cuisine-breakfast-menu-eat-food-logo-eating-thumbnail.png')
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def get_absolute_url(self):
        return reverse('food:item', kwargs=({'item_id': self.pk}))

    def __str__(self):
        return self.name
    

food-site/mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default_profile.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'

food-site/mysite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image']

food-site/mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food-site/mysite/food/views.py
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Item
from .forms import ItemForm


# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request,'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request, item_id: int):
    item = get_object_or_404(Item, pk=item_id)
    return render(request, 'food/item.html', {'item': item})


class AddItemView(CreateView):
    model = Item
    template_name = 'food/item_form.html'
    fields = ['name', 'description', 'price', 'image']

    def form_valid(self, form):
        item_form_instance: Item = form.instance
        item_form_instance.user_name = self.request.user
        return super().form_valid(form)


def edit_item(request, item_id: int):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item_form.html', {'form': form})


def delete_item(request, item_id: int):
    item = Item.objects.get(id=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item_delete.html', {'item': item})

food-site/mysite/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.

def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}! Your account has been created.')
            return redirect('login')
    else:
        form = RegisterForm()
        print(form)
    return render(request, 'users/register.html', {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return render(request, 'users/logout.html', {})


@login_required
def profile(request):
    return render(request, 'users/profile.html', {})

food-site/mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="#">Menu Item</a>
            <a class="nav-item nav-link" href="{% url 'food:add_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            <a class="nav-item nav-link" href="#">View Item</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>

</html>

food-site/mysite/food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block body %}

    {% for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="150px" src="{{item.image}}">
        </div>
        <div class="col-md-4">
            <h3>{{ item.name }}</h3>
            <h5>{{ item.description }}</h5>
            <h6>${{ item.price }}</h6>
            <h6>Added by: {{ item.user_name }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:item' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
    {% endfor %}

    {% endblock %}

</body>

</html>

food-site/mysite/food/templates/food/item.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="card" height="300px" src="{{ item.image }}">
            </div>
            <div class="col-md-6">
                <h3>{{ item.name }}</h3>
                <h5>{{ item.description }}</h5>
                <h6>${{ item.price }}</h6>
                <h6>Added: {{ item.user_name }}</h6>
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-primary">Delete</a>
            </div>
        </div>

        {% endblock %}
</body>

</html>

food-site/mysite/food/templates/food/item_delete.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ item.name }}"?</p>
    <button type="submit">Delete</button>
</form>

{% endblock %}

food-site/mysite/food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Add item
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form%}
                        <div class="form-group">
                            {{ field.name|capfirst }}
                            <br />
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

food-site/mysite/users/templates/users/login.html
{% extends 'food/base.html' %} <!--TODO: do not use anything from another app-->

{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Login
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form%}
                        <div class="form-group">
                            {{ field.name|capfirst }}
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

food-site/mysite/users/templates/users/logout.html
<h1>You have been logged out.</h1>

food-site/mysite/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" alt="{{ user.username }}" width="400px">

food-site/mysite/users/templates/users/register.html
{% extends 'food/base.html' %} <!--TODO: do not use anything from another app-->

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Register
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form%}
                        <div class="form-group">
                            {{ field.name|capfirst }}
                            <br />
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}